apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "mysqldb-mgr-istio.fullname" . }}-test-connection"
  labels:
    {{- include "mysqldb-mgr-istio.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['{{ include "mysqldb-mgr-istio.fullname" . }}:{{ .Values.service.port }}']
  restartPolicy: Never
