apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mysqldb-mgr-istio.labels" . | nindent 4 }}
type: Opaque
data:
  root-password: {{ .Values.mysql.rootPassword | toString | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-replica-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mysqldb-mgr-istio.labels" . | nindent 4 }}
type: Opaque
data:
  replica-account: {{ .Values.mysql.replicationUser | toString | b64enc }}
  replica-password: {{ .Values.mysql.replicationPassword | toString | b64enc }}
