apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mysqldb-mgr-istio.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: {{ .Values.service.port }}
    name: mysql
  - port: {{ .Values.service.mgrPort }}
    name: mgr
  selector:
    {{- include "mysqldb-mgr-istio.selectorLabels" . | nindent 4 }}
